# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ sources ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: sources

    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install NPM dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Copy README into build
      run: cp README.md build/README.md

    - name: Init git and commit in build
      working-directory: build
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Action"
        git init
        git add -A
        git commit -m 'deploy'

    - name: Push build to master
      uses: ad-m/github-push-action@master
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        # repository: # optional, default is
        # Destination branch to push changes
        branch: master
        # Determines if force push is used
        force: true
        # Directory to change to before pushing.
        directory: build




